// starters/nuxt/app.vue
<script setup>
import { site } from "./site.config";

const { member, status, refresh } = useMember();
const { $memberstack } = useNuxtApp();
const route = useRoute();

// Resolve the session once, when the app mounts. Pages gated by the `gated`
// middleware may have resolved it already; refresh() is cheap and idempotent.
onMounted(() => {
  if (status.value === "loading") refresh();
});

useHead({ title: site.name });

const logout = async () => {
  await $memberstack.logout();
  await refresh();
  navigateTo("/");
};
</script>

<template>
  <header class="nav">
    <NuxtLink to="/" class="brand">{{ site.name }}</NuxtLink>

    <nav class="nav-links">
      <!--
        ClientOnly, because who is signed in is a fact only the browser has.
        The Memberstack SDK reads a cookie in the browser, so the server render
        can never know it and always emits the signed-out nav.

        Without this wrapper Nuxt logs "Hydration completed but contains
        mismatches": the `gated` middleware resolves the session during
        hydration, so the client renders a different nav than the server sent.
        Nuxt then patches the DOM, which is exactly the flicker this is meant to
        avoid.

        The fallback is deliberately empty rather than a signed-out nav — a
        member reloading a page should not see "Log in" for a frame.
      -->
      <ClientOnly>
        <template v-if="status === 'loading'" />
        <template v-else-if="member">
          <NuxtLink to="/members" :class="{ active: route.path === '/members' }">
            Members
          </NuxtLink>
          <NuxtLink to="/account" :class="{ active: route.path === '/account' }">
            Account
          </NuxtLink>
          <button type="button" class="btn btn-ghost" @click="logout">
            Log out
          </button>
        </template>
        <template v-else>
          <NuxtLink to="/login">Log in</NuxtLink>
          <NuxtLink to="/signup" class="btn btn-primary btn-sm">Sign up</NuxtLink>
        </template>
      </ClientOnly>
    </nav>
  </header>

  <main>
    <NuxtPage />
  </main>

  <footer class="foot">
    <span>
      {{ site.name }} is a Memberstack starter. Replace
      <code>site.config.js</code> with your own and this becomes your site.
    </span>
  </footer>
</template>

// starters/angular/src/app/app.component.ts
import { Component, inject } from "@angular/core";
import { Title } from "@angular/platform-browser";
import { Router, RouterLink, RouterLinkActive, RouterOutlet } from "@angular/router";
import { site } from "../site.config";
import { MemberService } from "./member.service";

@Component({
  selector: "app-root",
  standalone: true,
  imports: [RouterOutlet, RouterLink, RouterLinkActive],
  template: `
    <header class="nav">
      <a routerLink="/" class="brand">{{ site.name }}</a>

      <nav class="nav-links">
        <!-- Rendering nothing while the session resolves keeps the nav from
             flickering "Log in" at a member who is already signed in. -->
        @if (members.status() !== "loading") {
          @if (members.member()) {
            <a routerLink="/members" routerLinkActive="active">Members</a>
            <a routerLink="/account" routerLinkActive="active">Account</a>
            <button type="button" class="btn btn-ghost" (click)="logout()">
              Log out
            </button>
          } @else {
            <a routerLink="/login">Log in</a>
            <a routerLink="/signup" class="btn btn-primary btn-sm">Sign up</a>
          }
        }
      </nav>
    </header>

    <main><router-outlet /></main>

    <footer class="foot">
      <span>
        {{ site.name }} is a Memberstack starter. Replace
        <code>site.config.ts</code> with your own and this becomes your site.
      </span>
    </footer>
  `,
})
export class AppComponent {
  readonly members = inject(MemberService);
  private readonly router = inject(Router);
  readonly site = site;

  constructor() {
    // index.html is static, so the tab title comes from site.config here
    // rather than being hardcoded in two places that can drift apart.
    inject(Title).setTitle(site.name);

    // Resolve the session once at startup. Gated routes may have resolved it
    // already via the guard; refresh() is cheap and idempotent.
    if (this.members.status() === "loading") this.members.refresh();
  }

  async logout() {
    await this.members.logout();
    this.router.navigate(["/"]);
  }
}
